=== fglichttechnik/Radiance-RoadLighting-Simulation-Framework/RoadRad/src/LMKSetMat.dtd
<!ELEMENT LMKSetMat (Description, StreetSurface, LMKData+)>

<!ELEMENT Description (SceneTitle, FocalLength, ViewPoint, Target, ScotopicToPhotopicRatio, Pole)>
<!ELEMENT SceneTitle (#PCDATA)>
<!ATTLIST SceneTitle
    Title CDATA #REQUIRED
>
<!ELEMENT FocalLength (#PCDATA)>
<!ATTLIST FocalLength
    FL CDATA #REQUIRED
>
<!ELEMENT ViewPoint (#PCDATA)>
<!ATTLIST ViewPoint
    Distance CDATA #REQUIRED
>
<!ELEMENT Target (#PCDATA)>
<!ATTLIST Target
    Size CDATA #REQUIRED
>
<!ELEMENT ScotopicToPhotopicRatio (#PCDATA)>
<!ATTLIST ScotopicToPhotopicRatio
    SPRatio CDATA #REQUIRED
>
<!ELEMENT Pole (#PCDATA)>
<!ATTLIST Pole
    NumPoleFields CDATA #REQUIRED
>


<!ELEMENT StreetSurface (QuadrangleObject)>
<!ELEMENT QuadrangleObject (upperLeft, upperRight, lowerLeft, lowerRight)>
<!ELEMENT upperLeft (#PCDATA)>
<!ATTLIST upperLeft 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>
<!ELEMENT upperRight (#PCDATA)>
<!ATTLIST upperRight 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>
<!ELEMENT lowerLeft (#PCDATA)>
<!ATTLIST lowerLeft
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>
<!ELEMENT lowerRight (#PCDATA)>
<!ATTLIST lowerRight 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>


<!ELEMENT LMKData (dataSource+, RectObject)>
<!ELEMENT dataSource (#PCDATA)>
<!ATTLIST dataSource 
    src CDATA #REQUIRED
    type CDATA #REQUIRED
>
<!ELEMENT RectObject (upperLeft, lowerRight, border, position)>
<!ELEMENT upperLeft (#PCDATA)>
<!ATTLIST upperLeft 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>
<!ELEMENT lowerRight (#PCDATA)>
<!ATTLIST lowerRight 
    x CDATA #REQUIRED
    y CDATA #REQUIRED
>
<!ELEMENT border (#PCDATA)>
<!ATTLIST border
    pixel CDATA #REQUIRED
>
<!ELEMENT position (#PCDATA)>
<!ATTLIST position 
    p CDATA #REQUIRED
>

=== fglichttechnik/Radiance-RoadLighting-Simulation-Framework/RoadRad/scenes/sceneXY/LMKSetMat/pos.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE LMKSetMat SYSTEM "LMKSetMat.dtd">

<LMKSetMat>
<LMKData>
<dataSource src="out0.mat" type="mat"/>
<RectObject>
<upperLeft x="517" y="247"/>
<lowerRight x="499" y="230"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out1.mat" type="mat"/>
<RectObject>
<upperLeft x="516" y="241"/>
<lowerRight x="499" y="228"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out2.mat" type="mat"/>
<RectObject>
<upperLeft x="514" y="242"/>
<lowerRight x="499" y="227"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out3.mat" type="mat"/>
<RectObject>
<upperLeft x="513" y="240"/>
<lowerRight x="499" y="226"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out4.mat" type="mat"/>
<RectObject>
<upperLeft x="513" y="235"/>
<lowerRight x="499" y="225"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out5.mat" type="mat"/>
<RectObject>
<upperLeft x="512" y="234"/>
<lowerRight x="499" y="223"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out6.mat" type="mat"/>
<RectObject>
<upperLeft x="511" y="235"/>
<lowerRight x="499" y="223"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out7.mat" type="mat"/>
<RectObject>
<upperLeft x="511" y="229"/>
<lowerRight x="499" y="222"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out8.mat" type="mat"/>
<RectObject>
<upperLeft x="510" y="232"/>
<lowerRight x="499" y="221"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out9.mat" type="mat"/>
<RectObject>
<upperLeft x="509" y="231"/>
<lowerRight x="499" y="220"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out10.mat" type="mat"/>
<RectObject>
<upperLeft x="509" y="229"/>
<lowerRight x="499" y="220"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out11.mat" type="mat"/>
<RectObject>
<upperLeft x="508" y="229"/>
<lowerRight x="499" y="219"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out12.mat" type="mat"/>
<RectObject>
<upperLeft x="508" y="227"/>
<lowerRight x="499" y="219"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>

<LMKData>
<dataSource src="out13.mat" type="mat"/>
<RectObject>
<upperLeft x="508" y="227"/>
<lowerRight x="499" y="218"/>
<border pixel="0"/>
<position p="--"/>
</RectObject>
</LMKData>
